#!/usr/bin/env python3
"""Bundle src/*.js into dist/main.js for the Obsidian plugin.

Dependency-free and deterministic: every CommonJS module in src/ is wrapped in
a function, modules are emitted in sorted order, and local requires
('./name') are resolved inside the bundle. The only external module allowed is
'obsidian', which Obsidian provides at runtime.

    python3 build.py           # write dist/main.js
    python3 build.py --check   # rebuild in memory; fail if dist/main.js differs
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
DIST = ROOT / "dist" / "main.js"
ENTRY = "main"
EXTERNAL = {"obsidian"}
REQUIRE = re.compile(r"""\brequire\(\s*(['"])([^'"]+)\1\s*\)""")
NAME = re.compile(r"^[a-z][a-z0-9-]*$")


def fail(message):
    print("build.py: " + message, file=sys.stderr)
    sys.exit(1)


def load_modules():
    modules = {}
    for path in sorted(SRC.glob("*.js")):
        name = path.stem
        if not NAME.match(name):
            fail(f"module file name not allowed: {path.name}")
        text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if not text.endswith("\n"):
            text += "\n"
        modules[name] = text
    if ENTRY not in modules:
        fail(f"missing entry module src/{ENTRY}.js")
    return modules


def check_requires(modules):
    """Every require is either 'obsidian' or an existing local module."""
    for name, text in modules.items():
        for match in REQUIRE.finditer(text):
            target = match.group(2)
            if target in EXTERNAL:
                continue
            if not target.startswith("./"):
                fail(f"src/{name}.js requires '{target}'; only './module' and 'obsidian' are allowed")
            local = target[2:]
            if local.endswith(".js"):
                local = local[:-3]
            if local not in modules:
                fail(f"src/{name}.js requires missing module '{target}'")


def reachable(modules):
    """Modules reachable from the entry, so unused files are not shipped."""
    seen, stack = set(), [ENTRY]
    while stack:
        name = stack.pop()
        if name in seen:
            continue
        seen.add(name)
        for match in REQUIRE.finditer(modules[name]):
            target = match.group(2)
            if target.startswith("./"):
                local = target[2:]
                stack.append(local[:-3] if local.endswith(".js") else local)
    return sorted(seen)


def bundle():
    manifest = json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))
    modules = load_modules()
    check_requires(modules)
    parts = [
        "'use strict';\n",
        f"/* {manifest['name']} {manifest['version']}. Generated by build.py from src/; do not edit by hand. */\n",
        "/* MIT License; see LICENSE and THIRD_PARTY.md. */\n",
        "const __modules = {\n",
    ]
    for name in reachable(modules):
        parts.append(f"{json.dumps(name)}: function (module, exports, require) {{\n")
        parts.append(modules[name])
        parts.append("},\n")
    parts.append(
        "};\n"
        "const __cache = {};\n"
        "function __load(name) {\n"
        "  if (__cache[name]) return __cache[name].exports;\n"
        "  const mod = { exports: {} };\n"
        "  __cache[name] = mod;\n"
        "  __modules[name](mod, mod.exports, id => id.startsWith('./') ? __load(id.slice(2).replace(/\\.js$/, '')) : require(id));\n"
        "  return mod.exports;\n"
        "}\n"
        f"module.exports = __load({json.dumps(ENTRY)});\n"
    )
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if dist/main.js is not up to date")
    args = parser.parse_args()
    output = bundle().encode("utf-8")
    if args.check:
        if not DIST.exists():
            fail("dist/main.js is missing; run python3 build.py")
        if DIST.read_bytes() != output:
            fail("dist/main.js is out of date; run python3 build.py and commit the result")
        print(f"dist/main.js is up to date ({len(output):,} bytes)")
        return
    DIST.parent.mkdir(parents=True, exist_ok=True)
    DIST.write_bytes(output)
    print(f"wrote dist/main.js ({len(output):,} bytes)")


if __name__ == "__main__":
    main()
