'use strict';

// Loads the committed dist/main.js in a fresh vm context with a fake
// 'obsidian' module (as Obsidian would load it), then runs the same
// end-to-end scenario as view.test.js against the bundle.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { test, run } = require('./helpers/harness');
const fakes = require('./helpers/fakes');
const { runScenario } = require('./helpers/scenario');

const root = path.join(__dirname, '..');
const distPath = path.join(root, 'dist', 'main.js');
const dist = fs.readFileSync(distPath, 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));

function loadBundle() {
  const context = { console, setTimeout, clearTimeout, setInterval, clearInterval, performance };
  const env = fakes.installGlobals(context);
  const module = { exports: {} };
  const requested = [];
  context.module = module; context.exports = module.exports;
  context.require = id => { requested.push(id); if (id === 'obsidian') return fakes.obsidian; throw new Error('unexpected require: ' + id); };
  vm.createContext(context);
  vm.runInContext(dist, context, { filename: 'dist/main.js' });
  return { PluginClass: module.exports, env, requested };
}

// The bundling rule of build.py, restated: every module reachable from
// src/main.js, wrapped in a function, in sorted order, between a fixed
// header and loader. Comparing whole files proves the committed bundle is
// exactly what build.py writes for the current sources.
function expectedBundle() {
  const srcDir = path.join(root, 'src'), modules = {};
  for (const f of fs.readdirSync(srcDir).filter(f => f.endsWith('.js')).sort()) {
    let text = fs.readFileSync(path.join(srcDir, f), 'utf8').replace(/\r\n/g, '\n');
    if (!text.endsWith('\n')) text += '\n';
    modules[f.slice(0, -3)] = text;
  }
  const seen = new Set(), stack = ['main'];
  while (stack.length) {
    const name = stack.pop();
    if (seen.has(name)) continue;
    seen.add(name);
    for (const m of modules[name].matchAll(/\brequire\(\s*(['"])([^'"]+)\1\s*\)/g)) {
      if (m[2].startsWith('./')) { const local = m[2].slice(2); stack.push(local.endsWith('.js') ? local.slice(0, -3) : local); }
    }
  }
  const parts = ["'use strict';\n", '/* ' + manifest.name + ' ' + manifest.version + '. Generated by build.py from src/; do not edit by hand. */\n',
    '/* MIT License; see LICENSE and THIRD_PARTY.md. */\n', 'const __modules = {\n'];
  for (const name of Array.from(seen).sort()) parts.push(JSON.stringify(name) + ': function (module, exports, require) {\n', modules[name], '},\n');
  parts.push('};\nconst __cache = {};\nfunction __load(name) {\n  if (__cache[name]) return __cache[name].exports;\n  const mod = { exports: {} };\n  __cache[name] = mod;\n' +
    "  __modules[name](mod, mod.exports, id => id.startsWith('./') ? __load(id.slice(2).replace(/\\.js$/, '')) : require(id));\n" +
    '  return mod.exports;\n}\nmodule.exports = __load(' + JSON.stringify('main') + ');\n');
  return parts.join('');
}

test('dist/main.js is byte for byte what build.py writes for the current sources', () => {
  assert.ok(dist === expectedBundle(), 'dist/main.js is stale; run python3 build.py and commit the result');
});

test('dist/main.js contains every source module verbatim (bundle is not stale)', () => {
  const modules = fs.readdirSync(path.join(root, 'src')).filter(f => f.endsWith('.js'));
  for (const f of modules) {
    const text = fs.readFileSync(path.join(root, 'src', f), 'utf8');
    assert.ok(dist.includes('"' + f.replace(/\.js$/, '') + '": function (module, exports, require) {\n' + text), f + ' is bundled as committed; run python3 build.py');
  }
  assert.ok(dist.startsWith("'use strict';\n/* " + manifest.name + ' ' + manifest.version + '.'));
});

test('the bundle only requires the obsidian module', () => {
  const { requested } = loadBundle();
  assert.deepEqual(Array.from(new Set(requested)), ['obsidian']);
});

test('plugin class constructs; onload and onunload run without throwing', async () => {
  const { PluginClass } = loadBundle();
  assert.equal(typeof PluginClass, 'function');
  const app = fakes.createApp({});
  const plugin = new PluginClass(app, manifest);
  await plugin.onload();
  assert.equal(plugin.commands.length, 3);
  plugin.onunload();
});

test('full lifecycle against the bundle', async () => {
  const { PluginClass, env } = loadBundle();
  await runScenario({ PluginClass, env, label: 'dist' });
});

test('manifest matches the release contract', () => {
  assert.equal(manifest.id, 'context-layer-brain');
  assert.equal(manifest.name, 'Context Layer Brain View');
  assert.equal(manifest.version, '0.4.0');
  const holder = /Copyright \(c\) \d{4} (\S+)/.exec(fs.readFileSync(path.join(root, 'LICENSE'), 'utf8'))[1];
  assert.equal(manifest.author, holder, 'author is the project identity from LICENSE');
  assert.equal('authorUrl' in manifest, false);
  assert.equal(typeof manifest.isDesktopOnly, 'boolean');
  assert.match(manifest.minAppVersion, /^\d+\.\d+\.\d+$/);
  assert.equal(/obsidian/i.test(manifest.id), false, 'plugin ids must not contain "obsidian"');
});

run('dist');
